# =============================================
# Création de l'Adresse IP Publique Azure
# =============================================
---
# Créer l'adresse IP publique Azure
- name: Créer l'adresse IP publique Azure
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group.name }}"
    name: "{{ public_ip.name }}"
    allocation_method: "{{ public_ip.allocation_method }}"
    state: present
  register: pip_output

# Afficher le message de confirmation de l'adresse IP
- name: Afficher le message de confirmation de l'adresse IP
  ansible.builtin.debug:
    msg: "Adresse IP publique créée avec succès : {{ public_ip.name }}"

# Afficher les détails de l'adresse IP
- name: Afficher les détails de l'adresse IP
  ansible.builtin.debug:
    var: pip_output