---
# =============================================
# Création d'une infrastructure AWS complète
# =============================================
- name: Création d'une infrastructure AWS complète
  hosts: localhost
  gather_facts: false
  
  # Variables d'environnement
  vars_files:
    - vars/main.yml
    - vars/defaults.yml

  # Tâches à exécuter
  tasks:
    - name: Inclure les tâches de création du VPC
      ansible.builtin.import_tasks: tasks/01-create_vpc.yml

    - name: Inclure les tâches de création du Security Group
      ansible.builtin.import_tasks: tasks/02-create_security_group.yml

    - name: Inclure les tâches de création de l'instance EC2
      ansible.builtin.import_tasks: tasks/03-create_ec2.yml 