---
# =============================================
# Création du Réseau Virtuel dans AWS
# =============================================
- name: Create a new VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_block }}"
    region: "{{ aws_region }}"
  register: vpc

# Afficher les informations du VPC
- name: Afficher les informations du VPC
  ansible.builtin.debug:
    var: vpc

# Création du Sous-Réseau dans AWS
# =============================================
- name: Create a new Subnet
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ subnet_cidr }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
  register: subnet 

# Afficher les informations du sous-réseau
- name: Afficher les informations du sous-réseau
  ansible.builtin.debug:
    var: subnet