# =============================================
# Création du Disque dans GCP
# =============================================
---
# Créer le disque dans GCP
- name: Create Disk in GCP
  google.cloud.gcp_compute_disk:
    name: "{{ disk_name }}"
    size_gb: "{{ disk_size }}"
    source_image: "{{ source_image }}"
    zone: "{{ zone }}"
    state: present
  register: disk

# Afficher les informations du disque
- name: "Artifact the Disk vars"
  ansible.builtin.set_stats:
    data:
      disk: "{{disk}}"