---
- name: 02 Create Network 
  google.cloud.gcp_compute_network:
    name: "{{ network_name }}"
    auto_create_subnetworks: false
    state: present
  register: network

- name: "Artifact the Network vars"
  ansible.builtin.set_stats:
    data:
      network: "{{network}}"