# =============================================
# Création du Réseau dans GCP
# =============================================
---
# Créer le réseau dans GCP
- name: Create Network 
  google.cloud.gcp_compute_network:
    name: "{{ network_name }}"
    auto_create_subnetworks: false
    state: present
  register: network

# Afficher les informations du réseau
- name: "Artifact the Network vars"
  ansible.builtin.set_stats:
    data:
      network: "{{network}}"