# =============================================
# Création du Sous-Réseau dans GCP
# =============================================
---
# Créer le sous-réseau dans GCP
- name: 03 Create Subnet in Network
  google.cloud.gcp_compute_subnetwork:
    name: "{{ subnet_name }}"
    region: "{{ region }}"
    ip_cidr_range: "{{ subnet_cidr }}"
    network: "{{ network }}"
    state: present
  register: subnet

# Afficher les informations du sous-réseau
- name: "Artifact the Subnet vars"
  ansible.builtin.set_stats:
    data:
      subnet: "{{subnet}}"