# =============================================
# Création de l'Adresse IP Publique dans GCP
# =============================================
---
- name: 04 Create an IP Address
  google.cloud.gcp_compute_address:
    name: "{{ ip_name }}"
    region: "{{ region }}"
    state: present
  register: address

# Afficher les informations de l'adresse IP
- name: "Artifact the Subnet vars"
  ansible.builtin.set_stats:
    data:
      address: "{{address}}"