---
- name: 03 Create Subnet in Network
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a Subnet in the Network
      google.cloud.gcp_compute_subnetwork:
        name: "{{ subnet_name }}"
        region: "{{ region }}"
        ip_cidr_range: "{{ subnet_cidr }}"
        network: "{{ network }}"
        state: present
      register: subnet

    - name: "Artifact the Subnet vars"
      ansible.builtin.set_stats:
        data:
          subnet: "{{subnet}}"